# Generated by Django 3.2 on 2021-04-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0003_order_order_buff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_quant', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
