# Generated by Django 3.2 on 2021-04-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0004_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_buff',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order_buff',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(),
        ),
    ]
