# Generated by Django 3.2 on 2021-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0009_remove_customer_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='inv_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
