# Generated by Django 3.2 on 2021-04-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0010_customer_inv_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_name', models.CharField(max_length=20)),
                ('order_no', models.IntegerField()),
            ],
        ),
    ]
