# Generated by Django 3.2 on 2021-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0011_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='ph1',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='ph2',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='remarks',
            field=models.CharField(default='', max_length=100),
        ),
    ]
