# Generated by Django 3.2 on 2021-04-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0012_auto_20210416_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ph1',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ph2',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='supplier',
            name='remarks',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inv_no',
            field=models.IntegerField(default=0),
        ),
    ]
