# Generated by Django 3.2 on 2021-04-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0013_auto_20210416_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_buff',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inv_buff',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inv_buff',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_buff',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_buff',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_buff',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
