# Generated by Django 3.2 on 2021-04-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0015_auto_20210427_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inv_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order_buff',
            name='order_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='order_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
