from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('product/cancel', views.cancel),
    path('cancel', views.cancel),
    path('show_transactions', views.show_transactions),
    path('product/<prod_name>', views.product_trans),
    path('product/invoice/<inv_no>', views.show_details_inv),
    path('product/order/<order_no>', views.show_details_order),
    path('addproduct', views.addproduct, name='addproduct'),
    path('insertprod', views.insertprod),
    path('addcustomer_inv', views.addcustomer_inv),
    path('addsupplier_order', views.addsupplier_order),
    path('add_customer', views.add_customer),
    path('addcust', views.addcust),
    path('add_supplier', views.add_supplier),
    path('addsupp', views.addsupp),
    path('show_prod', views.show_prod),
    path('edit_prod/updateprod', views.updateproduct),
    path('edit_prod/cancel', views.cancel),
    path('edit_prod/<prod_id>', views.edit_prod),
    path('edit_supplier/updatesupp', views.updatesupp),
    path('edit_customer/updatecust', views.updatecust),
    path('edit_customer/home', views.cancel),
    path('edit_customer/cancel', views.cancel),
    path('edit_supplier/home', views.cancel),
    path('edit_supplier/cancel', views.cancel),
    path('edit_supplier/<supp_id>', views.edit_supp),
    path('edit_customer/<cust_id>', views.edit_cust),
    path('deletesupp/<supp_id>', views.deletesupp),
    path('deletecust/<cust_id>', views.deletecust),


    path('deleteprod/<prod_id>', views.deleteprod),
    path('show_supp', views.show_supp, name='show_supp'),
    path('show_cust', views.show_cust, name='show_cust'),
    path('customer/customer_list', views.customer_list),
    path('supplier/supplier_list', views.supplier_list),
    path('supplier/<supp_name>', views.supp_details),
    path('customer/<cust_name>', views.cust_details),

    #Invoices paths
    path('create_invoice', views.create_invoice, name='create_invoice'),
    path('inv_buff', views.inv_buff, name='inv_buff'),
    path('inv_addmore', views.inv_addmore),
    path('insertInv', views.insertInv),
    path('inv_list', views.inv_list, name='inv_list'),
    path('invoice/toinvlists', views.toinvlists),
    path('invoice/<inv_no>', views.inv_details, name='inv_details'),
    path('invoice/<inv_no>/edit_inv', views.edit_inv, name='edit_inv'),
    path('invoice/<inv_no>/<inv_upd_no>/update_inv', views.update_inv),
    path('invoice/<inv_no>/save_inv', views.save_inv),
    path('invoice/printinv/<inv_no>', views.printinv),
    path('print_inv_list', views.print_inv_list),

    #Order paths
    path('create_order', views.create_order, name='create_order'),
    path('order_buff', views.order_buff),
    path('order_addmore', views.order_addmore),
    path('insertOrder', views.insertOrder),
    path('order_list', views.order_list, name='order_list'),
    path('order/toorderlists', views.toorderlists),
    path('order/<order_no>', views.order_details, name='order_details'),
    path('order/<order_no>/edit_order', views.edit_order, name='edit_order'),
    path('order/<order_no>/<order_upd_no>/update_order', views.update_order),
    path('order/<order_no>/save_order', views.save_order),
    path('invoice/printorder/<order_no>', views.printorder),
    path('print_order_list', views.print_order_list),
    path('supplier/order/<order_no>', views.routeorder),
    path('customer/invoice/<inv_no>', views.routeinv),
]
